CREATE TABLE IF NOT EXISTS task
(
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title       VARCHAR(300) NOT NULL,
    description VARCHAR(300) NOT NULL,
    user_id     BIGINT       NOT NULL,
    status      VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login    VARCHAR(30)  NOT NULL UNIQUE,
    email    VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS role
(
    role_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    role    VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE CASCADE
);

